### ISSUE TITLE
dsp_ff vs dsp-ff

### ISSUE THREAD

**Issue by tcal-x** [SymbiFlow/yosys-f4pga-plugins#249]
@mkurc-ant  -- this may be a packaging issue -- I'm using `yosys` and `yosys-symbiflow-plugins` packages from litex-hub -- I get an error from Yosys:
```
ERROR: Can't load module `./dsp_ff': /media/tim/GIT/google/CFU-Playground/env/conda/envs/cfu-common/bin/../share/yosys/plugins/dsp_ff.so: cannot open shared object file: No such file or directory
```
but there is a file
```
/media/tim/GIT/google/CFU-Playground/env/conda/envs/cfu-common/bin/../share/yosys/plugins/dsp-ff.so
```

(note `dsp_ff.so` vs `dsp-ff.so`)

**Comment by mkurc-ant** [comment]
@tcal-x As of yesterday the conda package containing the plugin should be present with the `main` label. Now I can see that I made a typo in the PR description, the plugin file is named `dsp-ff.so` but the Yosys pass name is `dsp_ff`. So you should do `plugin -i dsp-ff` but then `dsp_ff` to use it.

**Comment by tcal-x** [comment]
Thanks @mkurc-ant that does resolve the issue for me.
